name: rcd.agency
favicon: null
layout_spectrum: 0.944732871837914
typography_spectrum: 0.6168229116592556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5477483468130231
  lightness: 0.007553923642262816
  saturation: 0.3331029375549406
  rhythmicContrast: 0.7836311350110918
purpose: []
